[build-system]
build-backend = "cmeel"
requires = ["cmeel[build]"]

[project]
dependencies = []
description = "cmeel distribution for fmt, a modern formatting library"
license = "MIT"
name = "cmeel-fmt"
requires-python = ">= 3.10"
version = "12.2.0"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-fmt"
repository = "https://github.com/cmake-wheel/cmeel-fmt.git"
upstream = "https://github.com/fmtlib/fmt"

[tool.cmeel]
configure-args = [
  "-DBUILD_SHARED_LIBS=ON",
  # failing on ubuntu arm
  "-DCMAKE_CTEST_ARGUMENTS=--exclude-regex;'chrono-test|unicode-test|xchar-test'"
]
has-sitelib = false
source = "fmt"

[tool.tomlsort]
all = true
